### ISSUE TITLE
请教大神，fart配置文件如何获取或编写？

### ISSUE THREAD

**Issue by wwwtete** [hanbinglengyue/FART#10]

**Comment by hanbinglengyue** [comment]
提供的有测试的app和fart配置文件，文件内容为待脱壳app的包名

**Comment by wwwtete** [comment]
首先，非常感谢大神的回复，有一点没有看明白，请问我如何才能将待脱壳app的包名写到fart配置文件中？还是直接使用您提供的fart配置文件即可？

> 提供的有测试的app和fart配置文件，文件内容为待脱壳app的包名
