### ISSUE TITLE
ins

### ISSUE THREAD

**Issue by Minxin** [hanbinglengyue/FART#6]

**Comment by Minxin** [comment]
目录下未生成函数体ins.bin文件

**Comment by hanbinglengyue** [comment]
请确认下你的fart配置文件是否有问题，建议最好在linux下编辑，win和linux对换行符的处理策略不同会导致配置文件识别出错

**Comment by Minxin** [comment]
> 请确认下你的fart配置文件是否有问题，建议最好在linux下编辑，win和linux对换行符的处理策略不同会导致配置文件识别出错

3Q，已解决，是换行符的问题。
